"""Add notification preferences and quiz timestamp

Revision ID: 364088420b58
Revises: 
Create Date: 2025-07-30 14:09:49.742829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364088420b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gchat_webhook', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notification_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_time')
        batch_op.drop_column('gchat_webhook')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
